### ISSUE TITLE
Parent/child NS records mismatch for the v6ns zone

### ISSUE THREAD

**Issue by unriccio** [falling-sky/source#197] opened 2022-05-07 00:09 UTC
Hi!

While debugging #196 I noticed the following parent/child NS records mismatch:

```
$ dig +norec +additional NS v6ns.fra.test-ipv6.com @ns1.test-ipv6.com.

; <<>> DiG 9.16.4-Debian <<>> +norec +additional NS v6ns.fra.test-ipv6.com @ns1.test-ipv6.com.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27117
;; flags: qr; QUERY: 1, ANSWER: 0, AUTHORITY: 2, ADDITIONAL: 2

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;v6ns.fra.test-ipv6.com.		IN	NS

;; AUTHORITY SECTION:
v6ns.fra.test-ipv6.com.	300	IN	NS	v6ns.fra.test-ipv6.com.
v6ns.fra.test-ipv6.com.	300	IN	NS	v6ns1.fra.test-ipv6.com.

;; ADDITIONAL SECTION:
v6ns1.fra.test-ipv6.com. 300	IN	AAAA	2a00:dd80:20::322

;; Query time: 147 msec
;; SERVER: 2001:470:1:18::118#53(2001:470:1:18::118)
;; WHEN: sab mag 07 01:51:53 CEST 2022
;; MSG SIZE  rcvd: 219

$ dig +norec +additional NS v6ns.fra.test-ipv6.com @v6ns1.fra.test-ipv6.com.

; <<>> DiG 9.16.4-Debian <<>> +norec +additional NS v6ns.fra.test-ipv6.com @v6ns1.fra.test-ipv6.com.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7235
;; flags: qr aa; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 2

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 1623de62fc9fb225914d13e66275b4abcc997cce54d6d9b4 (good)
;; QUESTION SECTION:
;v6ns.fra.test-ipv6.com.		IN	NS

;; ANSWER SECTION:
v6ns.fra.test-ipv6.com.	300	IN	NS	v6ns1.fra.test-ipv6.com.

;; ADDITIONAL SECTION:
v6ns1.fra.test-ipv6.com. 300	IN	AAAA	2a00:dd80:20::322

;; Query time: 19 msec
;; SERVER: 2a00:dd80:20::322#53(2a00:dd80:20::322)
;; WHEN: sab mag 07 01:52:11 CEST 2022
;; MSG SIZE  rcvd: 127
```

Basically the parent says that both v6ns and v6ns1 are valid child while 1) there is no AAAA entry for v6ns and 2) v6ns1 says it's the only child.
This slows down the querying and is a bit misleading when trying to analyse/debug the DNS resolution.

The Zone File Generator seems to hint that the right setup should have just one child...
Could it be that the "v6ns NS v6ns" entry is an historical leftover that can be removed?
(the same seems to happen also for the "ams2" hosts, I didn't check others)

Thanks :)

**Comment by jfesler** [comment] 2022-05-08 19:49
Dupe of #196

**Closed by jfesler** 2022-05-08 19:49 UTC
